In [2]:
# import numpy library as 'np'
import numpy as np

In [4]:
# Create an array named 'arr' containing the values (1,2,3,4)
arr = np.array([1, 2, 3, 4])

In [6]:
# show values in (arr)
print(arr)

[1 2 3 4]


In [8]:
# show values in (arr) where each value is incremented by 2
print(arr + 2)

[3 4 5 6]


In [10]:
# show values in (arr) where each value is multiplied by 3
print(arr * 3)

[ 3  6  9 12]


In [12]:
# calculate the average of the values in (arr)
np.mean(arr)

2.5

In [14]:
# calculate the standard deviation of the values in (arr)
np.std(arr)

1.118033988749895

In [15]:
# reshape to a 2 dimentional array
arr.reshape(2, 2)

array([[1, 2],
       [3, 4]])